### ISSUE TITLE
Add realistic test case for `convolute_eko`

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/pineappl#122]
in order to not rely on a manual test (e.g. in `pineko`) we should add a proper test here, for that we need:
- a simple grid G: this can be a positivity-like grid with, e.g., `O1 = [u(x=0.1, Q2=100)]` with a sufficent, but not too big number of bins in x
- an EKO E: the "raw" eko should be sufficient to keep the actual library out of the game, say `E(10 <- 100)`
- a PDF set f: to make the grids/table collapse to numbers

the actual check would then be `f(Q0) x (E x G) = f(Q)`

this could also be reused for #108 

PS: corresponding email thread around Wed, Mar 02, 2022 at 11:27:26AM +0100

**Comment by cschwan** [comment]
@andreab1997 @AleCandido @felixhekhorn I'm now working on this and using <https://github.com/NNPDF/fktables/issues/32#issuecomment-1261956144> as a test case. By the way, the crate [ndarray_npy](https://docs.rs/ndarray-npy/latest/ndarray_npy/) is very handy to load the EKO.

**Comment by AleCandido** [comment]
> By the way, the crate [ndarray_npy](https://docs.rs/ndarray-npy/latest/ndarray_npy/) is very handy to load the EKO.

Good to know, it is one of those we considered for the Rust loader https://github.com/N3PDF/eko/issues/97
