### ISSUE TITLE
Improve `plot` subcommand

### ISSUE THREAD

**Issue by cschwan** [NNPDF/pineappl#147]
- [x] plot script is too complicated, especially the `data()` function can be done much more straightforward; this requires repeating the last datapoint for each slice in Rust (instead of in Python). Partially simplified in commit 8cc3bddb1222c6296d883108f87f42cd86feef23; final modifications in commits 0f17358892ee7dfb7d6de12d900ec769079bdf1c, 66abef03f109ad980a681eb9825930ffd6565912, 026b8b7af4228f896d158967c00d4728f0edcb16 and 0dd15af211c100d5bec885f52c86163121345c4c
- [ ] ~support plotting different slices in the same panel (see for instance https://github.com/N3PDF/yadism/issues/75#issue-700954479)~
- [x] add panel with absolute comparison of different PDF results; implemented in commit 766e9e2616b16889dcb46ca9d82262751d7fc5c1
- [x] add panels with absolute/relative contributions of different partonic channels. ~~How do we show negative contributions?~~ Commit c20a246c25224da9f1248b4fe95e347dda772551 shows the two most important channels and can easily be extended to show more

**Comment by AleCandido** [comment]
> - [ ] support plotting different slices in the same panel (see for instance https://github.com/N3PDF/yadism/issues/75#issue-700954479)

Just to point it out: that issue has already been marked twice as stale (even if we still believe it's relevant), so maybe not the best example...

**Comment by felixhekhorn** [comment]
> Just to point it out: that issue has already been marked twice as stale (even if we still believe it's relevant), so maybe not the best example...

True - but, if I remember correctly, we will inherit at some point plots from https://github.com/NNPDF/nnusf

**Comment by cschwan** [comment]
In commit 13be3ce474f34f7c228e7c8a7c1d4447da8e6c28, the style-related commands have been collected in the main function. In commits 13a93d2291afdb552f262e0f9b6977bae13757b9 and 4bd5268bb70f4592ff289bba514800124de4bd10 the main function itself has been simplified.
