### ISSUE TITLE
Python Distribution

### ISSUE THREAD

**Issue by alecandido** [NNPDF/pineappl#177]
Follow up of #176 

- [ ] prepare CI for release
- [ ] add [dependency](https://github.com/N3PDF/pineappl/pull/176#issuecomment-1249179607) on this new package in the `pineappl` Python package

The overall idea is to build everything in the CI, and supplement the current default PineAPPL package with CLI installation.

This partly address #129, since a quick binary installation will be available through `pip` (but it does not solve the problem of the C API).

**Comment by cschwan** [comment]
Done in #266.
