### ISSUE TITLE
Add pre-commit?

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/pineappl#180]
How about activating [pre-commit](https://pre-commit.com/) here? e.g. [this repo](https://github.com/doublify/pre-commit-rust/blob/master/.pre-commit-hooks.yaml) provides `fmt`, `check` and  `clippy`

**Comment by felixhekhorn** [comment]
I think we would only need to update if `cargo` would change, which is highly unlikely - in any case the hooks are very simple so we could even fork and maintain them ...

**Comment by cschwan** [comment]
I agree that using a git hook is potentially a good idea. Right now we only write what people should do in [`CONTRIBUTING.md`](https://github.com/N3PDF/pineappl/blob/master/CONTRIBUTING.md), with hooks we could automate/enforce it. However, it seems that [pre-commit](https://pre-commit.com/) is mostly tailored towards Python and probably a bit too much for what we need; let's talk about that first.

- Run `cargo fmt --check` to see if everything is properly formatted.
- We probably don't want to run `cargo clippy` now, as this returns a very long list of warnings. At some point, however, we might consider doing that.
- Do we want to run `cargo check`? If yes, do we want to run it with `--features=applgrid,fktable,fastnlo` or a subset of these (which would require having these libraries installed)?
- I don't think we want to run `cargo test`, which is a job for our CI.

An alternative to [pre-commit](https://pre-commit.com/) is writing the hooks manually, putting them into `.githooks/` and activating them with `git config core.hooksPath .githooks/`.

**Comment by AleCandido** [comment]
You are definitely right that `pre-commit` is coming from Python ecosystem, but in a sense is only the driver. Could have been written in shell or perl, and it was the same.

The main argument in favor of `pre-commit` is that simplifies a set of operations, and provide useful hooks out of the box. The main con is that it is definitely "non-minimal".

The minimal solution would be `.githooks/`, but we are adding too much to it, at some we'll start rewriting `pre-commit`. At that point the minimality would be defeated by duplication.
