### ISSUE TITLE
Release workflow for binaries

### ISSUE THREAD

**Issue by alecandido** [NNPDF/pineappl#183]
Since we considered distributing CLI binaries in #176, and of course they will be for a specific platform, I believe we can provide a partial solution to #129, just with a releasing workflow (like `wheels.yml`, but for Rust).

I believe I can provide quickly a first draft, and I will try in a while. I'm writing this issue just to collect some info.

### Workflow

We can copy an already working one, like:
https://github.com/r-darwish/topgrade/blob/master/.github/workflows/release.yml

*In the same repo (same folder) there is a similar workflow for cross compilation. It's not more complicated, but I don't like to maintain this kind of things, so this is where I put my personal threshold.*

**Comment by AleCandido** [comment]
Essentially, I just found an old note, and pasted here with a little context...
