### ISSUE TITLE
Raise versions of `pineappl_applgrid` and `pineappl_fastnlo` to match `pineappl`'s

### ISSUE THREAD

**Issue by cschwan** [NNPDF/pineappl#189]
For some reason I decided to decouple the version numbers of `pineappl_applgrid` and `pineappl_fastnlo` from the `pineappl`, `pineappl_capi`, `pineappl_cli` and `pineappl_py`. This isn't a good idea because in this way we have to release them manually, meaning `./make_release.sh` don't cover them. Before releasing the next version we should simply increase their version numbers.

**Comment by AleCandido** [comment]
I suggest to change this line:
https://github.com/NNPDF/pineappl/blob/ecb140aa1a432a1f2797e52eca921f6b58a13e98/make_release.sh#L83
and actually store them in a variable, just not to make them hidden in the middle of the script.

Also this part should make use of the variable and do a loop:
https://github.com/NNPDF/pineappl/blob/ecb140aa1a432a1f2797e52eca921f6b58a13e98/make_release.sh#L91-L111
just split the first one, or maybe better branch if the name is exactly `pineappl` to wait 60s.

**Comment by cschwan** [comment]
@AleCandido good points, I also changed the feature checks in commit 58158e6d97f8e6a8a5b52d27743dd7b9b1924a06.
