### ISSUE TITLE
Remove/fix `prettytable-rs` dependency

### ISSUE THREAD

**Issue by cschwan** [NNPDF/pineappl#195]
[Recently](https://github.com/actions/runner-images/issues/6399), `ubuntu-latest` was switched from `ubuntu-20.04` to `ubuntu-22.04`, which seems to break `pineappl`. It segfaults, see <https://github.com/NNPDF/pineappl/actions/runs/3646167214/jobs/6156975988>. My bet is that it's not caused by `pineappl` itself but rather by a dependency.

**Comment by AleCandido** [comment]
I can tell you that I could compile PineAPPL on my local Ubuntu 22.04, I did it many times.

**Comment by cschwan** [comment]
Yes, it's not quite that easy. What I noticed is that it started breaking when the switch happened, but it's still there with `ubuntu-20.04`.

It seems that `pineappl [subcommand] --help` is fine, while operations involving convolutions segfault: <https://github.com/NNPDF/pineappl/actions/runs/3646494375/jobs/6157637600>.

**Comment by AleCandido** [comment]
I had a look to the logs, but it is highly non-trivial.
Especially, I do not see what they all have in common: consider that also commands like `pineappl obl` are failing, and no convolution should be involved there.

**Comment by cschwan** [comment]
True, that is even weirder.

**Comment by cschwan** [comment]
I can reproduce a segfault with Rust nightly, which segfaults in `prettytable::Table::printstd` - that makes sense with the observations above, they all print a table using [prettytable-rs](https://crates.io/crates/prettytable-rs).

**Comment by AleCandido** [comment]
I agree it matches the observation, but is the CI running with Nightly?

**Comment by cschwan** [comment]
Yes, it was. It seems to work with stable. I think the problem is `prettytable-rs`, however, and Rust nightly is probably more strict than stable (in some way I don't know). Since you can't produce segfaults in Rust unless you use unsafe, my bet is on

https://github.com/phsym/prettytable-rs/blob/e159600d999f55f49fa9141e1a014d776a67c836/src/lib.rs#L513-L518

I can confirm that this piece of code is called.

**Comment by AleCandido** [comment]
Interestingly enough, the guy wrote:
```rs
// All this is a bit hacky. Let's try to find something else
```
on May 29, 2017, and it's still there.

It looks a good candidate to break with new versions. Essentially, it is recasting an immutable reference to a table to a mutable one, to perform a single operation. But that's an entry point for plenty of issues.

**Comment by AleCandido** [comment]
Ok, it seems like there is already an issue open mentioning it https://github.com/phsym/prettytable-rs/issues/145.
Is this matching the usage in `pineappl_cli`? @cschwan

**Comment by cschwan** [comment]
Yes, I'm pretty sure that's the cause.

**Comment by pinkforest** [comment]
You can just bump prettytable-rs to 0.10 - I've pushed a release :)

**Comment by cschwan** [comment]
@pinkforest I'm already on it, thanks!
