### ISSUE TITLE
Improve Python interface

### ISSUE THREAD

**Issue by alecandido** [NNPDF/pineappl#200]
There are a bunch of items that can be improved in the Python interface, eventually leading to less code to maintain and better DX for `pineappl_py` consumers:

- [x] drop Python layer, i.e. `pineappl_py/pineappl`, since at this point we have enough tools in PyO3 ecosystem ([`pyo3`](https://github.com/PyO3/pyo3), [`rust-numpy`](https://github.com/PyO3/rust-numpy), and extras, e.g. [logging](https://pyo3.rs/v0.17.3/ecosystem/logging.html), if ever any of these will be needed) to provide a Python native experience without a dedicated layer (we can work with numpy arrays, add static/classmethods, and getters and setters with properties)
- [x] code generation: a lot of bindings are really repetitive, and it is clear we can automate many of them; PyO3 itself is [based on code generation](https://pyo3.rs/v0.17.3/rust_cpython.html#macros), but mainly targeting Rust-powered Python libs, not bindings for standalone Rust libs, so we should clutter `pineappl` crate with PyO3 declarative macros; this is rather ugly, because then we might want to do the same for C bindings, and further ones in case we will ever support new languages (so scaling the number of macros with the languages supported); so either we find a native way to generate code using PyO3 macros, or we should write our own macros to generate the code corresponding to repeated patterns in current content of `pineappl_py/src`
- [ ] Python types: types are useful in Rust as in Python, so, if possible, let's propagate them to the second, even though PyO3 still indicates [a manual approach](https://pyo3.rs/v0.17.3/python_typing_hints.html)
- [ ] better Python exceptions: we can use PyO3 support for [plain exceptions](https://pyo3.rs/v0.17.3/exception.html), or its [`anyhow` feature](https://pyo3.rs/v0.17.3/features.html#anyhow), since @cschwan already started introducing `anyhow` in main `pineappl` crate

**Comment by cschwan** [comment]
Here's another take on this: <https://towardsdatascience.com/nine-rules-for-writing-python-extensions-in-rust-d35ea3a4ec29>.

**Comment by AleCandido** [comment]
> Here's another take on this: [towardsdatascience.com/nine-rules-for-writing-python-extensions-in-rust-d35ea3a4ec29](https://towardsdatascience.com/nine-rules-for-writing-python-extensions-in-rust-d35ea3a4ec29).

I need some time to digest. If you already did (or you will do before), can you turn the content of the article in further points in the OP? (or a separate message if you like more)

**Comment by cschwan** [comment]
I was more a reminder for myself to read it :smiley:. I also saw it's an article from 2022, so I probably linked it before (I vaguely recall doing that).

**Comment by Radonirinaunimi** [comment]
With other burdens out of the way, I can now put this in the priority list. Will also need some time to digest everything above but will dive into the actual changes soon.

**Comment by alecandido** [comment]
This issue is pretty old, and PyO3 is quickly evolving. Please, check the newly available features before attempting any implementation :)

**Comment by Radonirinaunimi** [comment]
Thanks both! I will have a look.

**Comment by cschwan** [comment]
I think this is pretty much done in #299, for everything else we should open a new Issue.
