### ISSUE TITLE
MSRV not supported on rtd

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/pineappl#203]
Starting from https://github.com/NNPDF/pineappl/commit/fd31cc223241b19fc9b54a5404470e026e526f9e the MSRV is 1.65, which however is [not supported on rtd](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-rust): the available version are `1.55,1.61,1.64` - this causes [the python documentation to fail](https://readthedocs.org/projects/pineappl/builds/19084095/) - I guess there is nothing we can do ... (except maybe ask the rtd staff if they are willing to upgrade, but since Rust is rolling release I wonder if they are willing to ...)

**Comment by AleCandido** [comment]
They are [constantly upgrading](https://github.com/readthedocs/readthedocs.org/pull/9268).
Some time ago there was not even 1.64, they are simply much slower than stable.

**Comment by cschwan** [comment]
This has been fixed with commit 0c8164776c6cfe881a4820cf4d2f53a490433c68, cc593eb446402955f37530396a83c82e828086a8 and fc50e9c5d785076968f52ad9b913e32c0415bfa5.

**Comment by AleCandido** [comment]
<img width="508" alt="image" src="https://user-images.githubusercontent.com/10830876/220594660-60541b70-6f2d-4533-a732-3864efe460af.png">

Thanks!
