### ISSUE TITLE
Handle zero EKO passed to `Grid::evolve`

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/pineappl#204]
As @andreab1997 detected: when evolving with an EKO which is all 0s (by mistake) this results in an invalid FK table with no orders (and so the `NonTrivialOrder` error is returned). The new `evolve` somewhere discards operators which are 0 everywhere to gain speed - this is just fine.

However, if the EKO is *all* 0s we should either complain (maybe preferred) or return a valid FK table which is 0 everywhere.

**Comment by cschwan** [comment]
I agree, and I will take care of that. Note that all fixes will go into version `0.6.x`.

**Comment by cschwan** [comment]
Should be fixed in commit 91924356b1a2b0db4d9ee6036222ecb4a595cc40. Reopen if that isn't the case.
