### ISSUE TITLE
Consider adding jupyter integration

### ISSUE THREAD

**Issue by cschwan** [NNPDF/pineappl#205]
We should evaluate whether it's worth the effort to integrate the PineAPPL into jupyter. For instance the CLI mainly produces tables, through prettyprint-rs, which has support for [evcxr](https://crates.io/crates/prettytable-rs#evcxr-integration).

**Comment by cschwan** [comment]
> If you want to use Jupyter as a development tool, it might be an idea. Otherwise, I'd go for binding as much as possible to Python, and emit Pandas dataframes, that is what people using Jupyter are used to.

That's what I had in mind, or something similar for [R](https://www.r-project.org/), which I think also has a jupyter notebook, or even both.

**Comment by AleCandido** [comment]
> That's what I had in mind, or something similar for [R](https://www.r-project.org/), which I think also has a jupyter notebook, or even both.

Jupyter literally means "JUlia PYThon & R", but the biggest audience is definitely Python.

**Comment by cschwan** [comment]
I see, I didn't know that - anyway, R is great if you do what I do!
