### ISSUE TITLE
Problem with Python deployment

### ISSUE THREAD

**Issue by cschwan** [NNPDF/pineappl#211]
The Python deployment currently doesn't work, because maturin is too old. We need at least `0.13.4`, see also commit fc50e9c5d785076968f52ad9b913e32c0415bfa5. @AleCandido, could you take care of this? Podman doesn't work reliably on my system at work and I'm not sure I can upload it.

**Comment by cschwan** [comment]
@andreab1997 this is probably causing <https://github.com/NNPDF/pineko/actions/runs/4292741468/jobs/7479555051> to fail.

**Comment by AleCandido** [comment]
> @andreab1997 this is probably causing [NNPDF/pineko/actions/runs/4292741468/jobs/7479555051](https://github.com/NNPDF/pineko/actions/runs/4292741468/jobs/7479555051) to fail.

There I believe there might be two problems:
- indeed, wheels for Linux have not been deployed https://pypi.org/project/pineappl/0.6.0a1/#files
- pre-releases have not been allowed in pyproject.toml for PineAPPL, but I don't know if with the exact number this option is not needed (however, we should always use `^x.y.z` rather than `x.y.z`)

I will update the container (but this is a rather simple task, just have a look here https://github.com/NNPDF/pineappl/tree/master/pineappl_py/package)

If possible, I'd also like to get rid of that container at some point, but at the moment the quickest option is just to update it...

**Comment by cschwan** [comment]
> If possible, I'd also like to get rid of that container at some point, but at the moment the quickest option is just to update it...

I was thinking of the same. We can use #208 for that, by basing the container on a manylinux image instead of the Rust image.

**Comment by AleCandido** [comment]
> We can use #208 for that, by basing the container on a manylinux image instead of the Rust image.

That is exactly the `maturin` container: it is just based on `manylinux` with Rust and Maturin installed.

Instead, I was thinking to revisit the [`maturin-action`](https://github.com/NNPDF/pineappl/blob/master/pineappl_py/package/Containerfile), most likely we can fully get rid of the whole container at all, and just delegate to it (it is also generate the workflow by itself).

**Comment by andreab1997** [comment]
Ok then let me know what I should do for [NNPDF/pineko/actions/runs/4292741468/jobs/7479555051](https://github.com/NNPDF/pineko/actions/runs/4292741468/jobs/7479555051)

**Comment by AleCandido** [comment]
@andreab1997 For what it concerns you, there has been no release yet. Unless you want to run tests on Windows.

**Comment by cschwan** [comment]
We now have a prerelease, however on MacOS only packages for Python 3.10 and 3.11 are available. We should double-check which are missing and add them.

**Comment by AleCandido** [comment]
> We now have a prerelease, however on MacOS only packages for Python 3.10 and 3.11 are available. We should double-check which are missing and add them.

It is a problem with the new workflow, since before we also had the MacOS wheels for 3.7, 3.8, and 3.9 https://pypi.org/project/pineappl/0.5.9/#files

**Comment by cschwan** [comment]
Let's address the Python version problems in this branch: <https://github.com/NNPDF/pineappl/pull/214>.

**Comment by cschwan** [comment]
I believe we fixed all problems we had, shall I try to make another prerelease to check the 'release' part of the Wheels CI, @AleCandido?

**Comment by cschwan** [comment]
I believe all problems have been fixed.

**Comment by AleCandido** [comment]
Thanks @cschwan
