### ISSUE TITLE
Idea: asciinema for the CLI tutorial

### ISSUE THREAD

**Issue by cschwan** [NNPDF/pineappl#225]
The CLI tutorial happens - unsurprisingly - mainly in the shell, so it would be an interesting idea to use <https://asciinema.org/> to show it running in a video container.

**Comment by AleCandido** [comment]
Concerning the "video container", GitHub's Markdown renderer supports videos, and even GIFs :)

E.g. https://github.com/alelievr/Mixture/ (it was the one cited by SO, and has both, but I have seen them in many other projects).
