### ISSUE TITLE
Add a logging system that records and prints warnings

### ISSUE THREAD

**Issue by cschwan** [NNPDF/pineappl#254]
Related Issues:

- <https://github.com/NNPDF/pineappl/issues/253>

**Comment by AleCandido** [comment]
Not exactly logging, but you could consider [`tracing`](https://github.com/tokio-rs/tracing) (*tracing* is a bit more than *logging*, but it might be useful in PineAPPL, e.g. to debug and profile new interfaces)

**Comment by cschwan** [comment]
In the meantime I think warnings aren't a good idea anymore. An operation should either succeed or fail.

**Comment by alecandido** [comment]
I arrived more or less to the same conclusion: warnings are mostly cluttering the output and ignored.
Instead, if you want to pass some further information down to your user, you should add that to the function output, not printing it on stdout.
