### ISSUE TITLE
Upgrade container to avoid problems with Node 20 used by Github actions

### ISSUE THREAD

**Issue by cschwan** [NNPDF/pineappl#296]
Making the `0.8.0` release failed: <https://github.com/NNPDF/pineappl/actions/runs/9804583913>. Commits e5e26e5cf175c51e41fbb0d303cf10d8979f3f3c and dc311a6c04ebb50a8e59ff36dad9ce8cf0b0c0f7 temporarily fix the problem, until some unspecified date: <https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/>.

The only problematic action is `release.yml` and it the relevant jobs are `capi-linux` and `cli-linux`. For both jobs we'd have to find a container with a GLIBC version old enough to support most systems, but new enough to support Node 20.

**Comment by cschwan** [comment]
Fixed in #297. An unfortunate consequence is that the CAPI and the CLI now require at least GLIBC 2.29, which is quite a jump from the previously supported 2.14. With a few tricks we can probably support GLIBC 2.28, but below 2.28 Node 20 doesn't work anymore, which is required by Github's actions.

**Comment by scarlehoff** [comment]
fwiw, this means that servers using Debian Buster cannot use pineappl  > 0.7.4 ... among which is the cluster in Milan :__(

**Comment by cschwan** [comment]
OK, then we have to do something about it. Can you please open a new Issue for that?
