### ISSUE TITLE
Make a conda release of v0.8.x

### ISSUE THREAD

**Issue by Radonirinaunimi** [NNPDF/pineappl#300]
Would it be possible to also have the conda release of `v0.8.0`? This would be needed for various tests in NNPDF (see for example https://github.com/NNPDF/nnpdf/pull/2110).

**Comment by cschwan** [comment]
Yes, we'd need to fix <https://github.com/conda-forge/pineappl-feedstock/pull/40> first to make that happen, but so far I haven't had the time to look into it.

**Comment by Radonirinaunimi** [comment]
Btw, @cschwan if you need someone to experiment with the macos feedstock please let me know.

**Comment by Radonirinaunimi** [comment]
Thanks, I will have a look.

**Comment by Radonirinaunimi** [comment]
I can both build the wheel and install it locally so I am not sure yet what is the issue. 

The only difference between what is in the remote and what I have locally is that even though I am also using `MacOsX_13`, given that my python (through conda) was compiled with an older platform the wheel has the following reference: `pineappl-0.8.1-cp312-cp312-macosx_10_12_x86_64.whl`. But I don't think this could make a difference.

One thing that I don't understand is that it seems that it is trying to install the wheel with a different python version from the (c)python from which the wheel was build: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=980538&view=logs&j=a8dee1cf-d17f-5cb0-b53f-4a93dfdbfb0c&t=d9dbf137-9a7f-5666-c60c-9e1b2fc31445&l=1616

I will still keep digging.

**Comment by cschwan** [comment]
@Radonirinaunimi I added you as a code owner to the conda-forge repository, so you should have write access now. Let me know if it doesn't work!

**Comment by Radonirinaunimi** [comment]
> @Radonirinaunimi I added you as a code owner to the conda-forge repository, so you should have write access now. Let me know if it doesn't work!

Perfect! Thanks @cschwan.

**Comment by cschwan** [comment]
@Radonirinaunimi I released 0.8.2 yesterday, so you can either abandon 0.8.1 and proceed with 0.8.2 (merging 0.8.2 will close the PR for 0.8.1) or you continue with 0.8.1 and repeat your changes with 0.8.2 after you've merged 0.8.1.

**Comment by Radonirinaunimi** [comment]
> @Radonirinaunimi I released 0.8.2 yesterday, so you can either abandon 0.8.1 and proceed with 0.8.2 (merging 0.8.2 will close the PR for 0.8.1) or you continue with 0.8.1 and repeat your changes with 0.8.2 after you've merged 0.8.1.

Yes, I am continuing directly with `0.8.2`. 

Some of the MacOS platforms are now working ([status](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=985815&view=results)) but there are still some failures.

**Comment by Radonirinaunimi** [comment]
The remaining error:
```bash
tar: Error opening archive: Unrecognized archive format
```
seems to be due to the `.tar.gz` not being downloaded properly. By re-running the actions, the failed ones now pass. 

I am not sure what could be done here as this is really unpredictable.

**Comment by Radonirinaunimi** [comment]
Now, everything passed ...

**Comment by scarlehoff** [comment]
You just need the package to compile in the CI once. Maybe leave an issue open in the feedstock to remind yourself of the issue, but once the package is compiled (and uploaded to conda-forge) the unpredictability doesn't matter anymore.

**Comment by Radonirinaunimi** [comment]
So, @cschwan, @scarlehoff I guess we can then merge https://github.com/conda-forge/pineappl-feedstock/pull/44?

**Comment by cschwan** [comment]
I'll merge it.

**Comment by cschwan** [comment]
I had a closer look into build logs and it seems that the version isn't properly set and therefore `curl` downloads from the wrong link.

**Comment by cschwan** [comment]
Very strange, it doesn't seem to be entirely reproducible. Should the error `'tar: Error opening archive: Unrecognized archive format'` appear again, check the previous output which looks similar to the folllowing:

```
prefix:  '$PREFIX'
target:  'x86_64-apple-darwin'
version: '0.8.2'
URL:     'https://github.com/NNPDF/pineappl/releases/download/v0.8.2/pineappl_capi-x86_64-apple-darwin.tar.gz'
```

Most likely the `version` field is wrong and therefore the URL also, which leads to the error message.

**Comment by cschwan** [comment]
@Radonirinaunimi @scarlehoff please check that v0.8.2 works via Conda and then please close the Issue.

**Comment by Radonirinaunimi** [comment]
That error is indeed very strange. I am not really sure what is going on here.

But the `v0.8.2` via conda now works fine, at least all the tests on nnpdf are now passing https://github.com/NNPDF/nnpdf/pull/2129. So, I think we can close the issue.
