### ISSUE TITLE
Explain `managed-lhapdf` config

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/pineappl#303]
Please add a prominent link here (meaning front page) (and potentially a short summary) to a document in https://github.com/cschwan/managed-lhapdf where you explain about the existence of `managed-lhapdf.toml`, what the available configurations are and how to shortcut `managed-lhapdf` to use my already existing LHAPDF directory.

As already explained 1. I don't want to have twice `NNPDF40_nnlo_as_01180_1000` (which is several GB) on my disk, but instead 2. I want the tons of debug PDFs I have created over the last years (such as `gonly` and friends)

**Comment by cschwan** [comment]
Yes, that's a fair requirement. However, by default it should already reuse your existing LHAPDF directory. Are you telling me that isn't the case? That would be considered a bug.

**Comment by cschwan** [comment]
Let's continue the discussion here: <https://github.com/cschwan/managed-lhapdf/issues/2>.
