### ISSUE TITLE
Inconsistent convolution information: `convolution_particle` vs. `initial_state`

### ISSUE THREAD

**Issue by LucianHL** [NNPDF/pineappl#316]
Hi, this is quite possibly only ever going to be an issue for me, as I have been converting some potentially reasonably old applgrids to pineappl grids. But in the first example I have tried with the NNPDF code for some reason in the configs data of the converted file `convolution_particle` is used for beam 1 and `initial_state` for beam 2, i.e. there is `convolution_particle_1` and `initial_state_2`. This is causing `pineparser.py` to crash when these are read in. Possibly this is better fixed at the conversion stage but in any case changing the relevant try statements to:

    try:
        parton1 = pine_rep.key_values()["convolution_particle_1"]
    except KeyError:
        parton1 = pine_rep.key_values()["initial_state_1"]

    try:
        parton2 = pine_rep.key_values()["convolution_particle_2"]
    except KeyError:
        parton2 = pine_rep.key_values()["initial_state_2"]

fixes it, so might be worth updating.

**Comment by Radonirinaunimi** [comment]
> @Radonirinaunimi whether to add the code in the OP to `pineparser.py` here I leave it to you (i.e., whether you prefer to make sure that "broken" grids do not work so that they need to be fixed in some way; I favour a bit this option but woudn't mind putting the if-else that @LucianHL wrote if that's easier)

Just to say that I also favor the option of not allowing these mix in `pineparser.py` so we can keep the current way as it is.

**Comment by LucianHL** [comment]
Thank you @t7phy - yes that works as you suggested and no problem to work that into the conversion script for now. I will let you know if I have any issues running with these

**Comment by cschwan** [comment]
This problem has been reported before, but unfortunately I didn't find an Issue, which probably means it doesn't exist. So thank you for your report, @LucianHL!

The bug has been fixed in commit 741dcb936e70da3c7c83d21bc7b16d743b16a980, but there isn't a release with the fix yet. You probably don't want to use `master`, because it (intentionally) breaks the Python interface. I'll release `v0.8.4` with this fix soon.

**Comment by cschwan** [comment]
Here's a new release: <https://github.com/NNPDF/pineappl/releases/tag/v0.8.4>. @LucianHL, if you have the time please test whether this release has indeed fixed the observed behaviour. If that's the case, feel free to close the Issue.

**Comment by LucianHL** [comment]
Thank you - yes that installs fine and produces grids with the right convolution_particle labelling

**Comment by cschwan** [comment]
Great!
