### ISSUE TITLE
proton - antiproton collisions: issue with convolution_particle?

### ISSUE THREAD

**Issue by LucianHL** [NNPDF/pineappl#317]
Hi,

I would like to use a pineappl (and eventually fk) grid for p-pbar collisions. I would guess you simply change:

`convolution_particle_1: 2212`

to 

`convolution_particle_1: -2212`

or do this for `convolution_particle_2`. If the observable is rapidity symmetric then it should not (!?) matter which. Doing this for e.g. a total ttbar cross section grid via

`pineappl write --set-key-value convolution_particle_1 -2212 ...`

however gives a different result to 

`pineappl write --set-key-value convolution_particle_2 -2212 ...`

when running the usual 

`pineappl convolute ...`

command, i.e.

`convolution_particle_1: -2212
convolution_particle_2: 2212`

is different to 

`convolution_particle_1: 2212
convolution_particle_2: -2212`

 One of these (`convolution_particle_2 -2212`) agrees with the result of running 

`pineko compare ...`

where there is no dependence on ordering so one might guess the other is wrong somehow but in fact neither result agrees with my own implementation of this for convolutions with the applgrid files.

So I suspect I must be doing something wrong, but it also seems as though there might be an issue in the code here? My `pineko` installation is direct from 

`pip install 'pineko[nnpdf] @  git+https://github.com/nnpdf/pineko.git'`

while `pineappl` is from 

`cargo install --locked --features=applgrid pineappl_cli`

As a related aside, if there is a way to actually convolve pineappl grids with two different PDFs (one for each beam) that would provide a simple cross check (by modifying the LHAPDF grid directly to implement p -> pbar) but I can't see that this is possible?

**Comment by cschwan** [comment]
Hi @LucianHL, what you're doing is perfectly fine, but I presume you're using the 'wrong' grids. We usually optimize our grids (`pineappl write --optimize ...`), and this leads to a channel and subgrid symmetrization if the hadronic initial states are the same, like proton-proton.

The result of the optimization operation is a grid where you cannot change the hadron types anymore. You can check whether this is the case by looking at the channel definition:

    pineappl read --channels <GRID>

If you see quark-antiquark channels but not the tranposed ones, antiquark-quark, (or the other around) then this grid has been symmetrized.

If you've converted the grid from an APPLgrid, just repeat the conversion, but add the `--no-symmetrize` option to `pineappl import ...`. Then you should be able to convert this to a proton-antiproton grid.

You can convolve a grid with different PDFs if you pass the LHAPDF IDs or names separated by a `,` without any spaces.

**Comment by felixhekhorn** [comment]
I think this is similar to what I found also before [here](https://github.com/felixhekhorn/MaunaKea/blob/d857a363719a9e6f579f156948b483e4cbde3976/paper/corrections.py#L15)

```py
def change_collision(
    grid: pineappl.grid.Grid, id_a: int, pdf_a: lhapdf.PDF, id_b: int, pdf_b: lhapdf.PDF
) -> Sequence[float]:
    """Change collision system.

    We can reuse the same grid also for p-pbar collision if we adjust the PDG ID.
    We need to average over the two possibilities, as e.g. the LO (q-qbar) channel under
    charge conjungation of one hadron will become (ubar-ubar), (u,u), ...,
    but we only save a single combination (u,ubar), ... in the grid.
    """
    return (
        grid.convolute_with_two(
            id_a,
            pdf_a.xfxQ2,
            id_b,
            pdf_b.xfxQ2,
            pdf_a.alphasQ2,
        )
        + grid.convolute_with_two(
            id_b,
            pdf_b.xfxQ2,
            id_a,
            pdf_a.xfxQ2,
            pdf_a.alphasQ2,
        )
    ) / 2.0
```

except that I do the optimization already at grid creation time. So I agree with @cschwan this is just an eager optimization (that we want) and we need to counteract it now.

**Comment by LucianHL** [comment]
Many thanks both! Yes that works now though with `--no-optimize` rather than `--no-symmetrize`
