### ISSUE TITLE
Do not show scale-variation uncertainties when NLO log grids are not present

### ISSUE THREAD

**Issue by cschwan** [NNPDF/pineappl#46]
In this case the uncertainties are wrong.

**Comment by cschwan** [comment]
In general this isn't possible, because we can't reliably detect what LO and NLO is.

**Comment by felixhekhorn** [comment]
> In general this isn't possible, because we can't reliably detect what LO and NLO is.

that doesn't seem correct: you can determine what NLO is: a order is NLO if and only if there exists an other order with exactly one lower power of coupling (either a_s or a_em)

**Comment by cschwan** [comment]
@felixhekhorn I was thinking of the possibility that one can store LOs and NLOs in separate grids, but after thinking about it that's a special case that we don't want to support. I'm going to reopen this and change the CLI accordingly:

- if the grid is an FK table, then don't calculate scale variations
- if there are higher orders, starting at NLO there must at least be factorization-scale logs available, otherwise don't calculate scale variations (we might want to add a `--force` key to get the old behaviour)
